version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    target-branch: "main"
    labels:
      - "dependencies"
      - "azure"
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "org.springframework.boot:spring-boot*"
          - "org.springframework.security:spring-security*"
          - "org.springdoc:springdoc-openapi*"
        update-types:
          - "patch"
          - "minor"
      osdu-core:
        patterns:
          - "org.opengroup.osdu:os-core-common"
        update-types:
          - "patch"
          - "minor"
          - "major"
      azure:
        patterns:
          - "com.azure*"
          - "com.azure.spring*"
          - "com.microsoft.azure*"
          - "com.microsoft.graph*"
        update-types:
          - "patch"
          - "minor"
      build-tools:
        patterns:
          - "org.projectlombok:lombok"
          - "com.google.guava:guava"
        update-types:
          - "minor"
          - "patch"
      logging:
        patterns:
          - "org.apache.logging.log4j:*"
          - "ch.qos.logback:*"
          - "org.slf4j:*"
        update-types:
          - "minor"
          - "patch"
      data-format:
        patterns:
          - "com.fasterxml.jackson*"
          - "net.minidev:json-smart"
          - "com.google.code.gson:gson"
          - "org.yaml:snakeyaml"          
          - "org.json:json"
        update-types:
          - "minor"
          - "patch"
      common-utils:
        patterns:
          - "commons-beanutils:commons-beanutils"
          - "io.github.resilience4j:*"
          - "org.apache.commons:*"
          - "org.redisson:redisson"
          - "io.netty:*"
          - "io.lettuce:*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
  # 2) <service> CORE
  - package-ecosystem: "maven"
    directory: "/<service>-core"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    labels:
      - "dependencies"
      - "common"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      core-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 3) SPI AZURE
  - package-ecosystem: "maven"
    directory: "/provider/<service>-azure"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    labels:
      - "dependencies"
      - "azure"
    groups:
      azure-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
